import{asU8,concatBytes,readU16be,readU32be,u16be,u32be}from'./bits.js';import{decrypt,encrypt}from'./crypto.js';
export const FILE_MAGIC=new TextEncoder().encode('STEGOFL1');
export function buildFileTail(flag,filename,payload){const name=new TextEncoder().encode(filename),data=asU8(payload);if(flag!==0&&flag!==1)throw new RangeError('Flag must be 0 or 1');if(name.length>0xffff)throw new Error('檔名過長');return concatBytes(FILE_MAGIC,new Uint8Array([flag]),u16be(name.length),name,u32be(data.length),data);}
export async function appendFileToImage(imageBytes,fileBytes,filename,password=''){const payload=password?await encrypt(fileBytes,password):asU8(fileBytes);return concatBytes(imageBytes,buildFileTail(password?1:0,filename,payload));}
export function findMagicOffsets(value){const b=asU8(value),out=[];for(let i=0;i<=b.length-FILE_MAGIC.length;i++){let ok=true;for(let j=0;j<FILE_MAGIC.length;j++)if(b[i+j]!==FILE_MAGIC[j]){ok=false;break;}if(ok)out.push(i);}return out;}
export function tryParseTail(value,offset){const b=asU8(value);try{let p=offset+8;if(p+7>b.length)return null;const flag=b[p++];if(flag!==0&&flag!==1)return null;const nl=readU16be(b,p);p+=2;if(p+nl+4>b.length)return null;const filename=new TextDecoder('utf-8',{fatal:true}).decode(b.slice(p,p+nl));p+=nl;const length=readU32be(b,p);p+=4;if(p+length!==b.length)return null;return{flag,filename,payload:b.slice(p),offset};}catch{return null;}}
export function findValidTail(value){const offsets=findMagicOffsets(value);for(let i=offsets.length-1;i>=0;i--){const tail=tryParseTail(value,offsets[i]);if(tail)return tail;}return null;}
export function findPngBoundary(value){const b=asU8(value),sig=[137,80,78,71,13,10,26,10];if(b.length<20||sig.some((x,i)=>b[i]!==x))return null;let p=8;while(p+12<=b.length){const n=readU32be(b,p);if(n>b.length-p-12)return null;const type=String.fromCharCode(...b.slice(p+4,p+8));p+=12+n;if(type==='IEND')return n===0?p:null;}return null;}
export function findJpegBoundary(value){const b=asU8(value);if(b[0]!==255||b[1]!==216)return null;let p=2,inScan=false;while(p<b.length){if(!inScan){while(p<b.length&&b[p]===255)p++;if(p>=b.length)return null;const m=b[p++];if(m===217)return p;if(m===216||m===1||(m>=208&&m<=215))continue;if(p+2>b.length)return null;const len=readU16be(b,p);if(len<2||p+len>b.length)return null;if(m===218){p+=len;inScan=true;}else p+=len;}else{if(b[p++]!==255)continue;if(p>=b.length)return null;let m=b[p++];while(m===255&&p<b.length)m=b[p++];if(m===0||(m>=208&&m<=215))continue;if(m===217)return p;inScan=false;if(m===1)continue;if(p+2>b.length)return null;const len=readU16be(b,p);if(len<2||p+len>b.length)return null;if(m===218){p+=len;inScan=true;}else p+=len;}}return null;}
export function findRawImageBoundary(value){return findPngBoundary(value)??findJpegBoundary(value);}
export function guessExtension(value){const b=asU8(value);if(b.length>=4&&b[0]===80&&b[1]===75&&[3,5,7].includes(b[2])&&[4,6,8].includes(b[3]))return'zip';if(b.length>=4&&b[0]===37&&b[1]===80&&b[2]===68&&b[3]===70)return'pdf';if(b.length>=8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)return'png';if(b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)return'jpg';if(b.length>=2&&b[0]===31&&b[1]===139)return'gz';if(b.length>=4&&b[0]===82&&b[1]===97&&b[2]===114&&b[3]===33)return'rar';return'bin';}
export async function extractFileFromImage(value,password=''){const b=asU8(value),tail=findValidTail(b);if(tail){let payload=tail.payload;if(tail.flag===1){if(!password)throw new Error('此檔案已加密，請輸入密碼');payload=await decrypt(payload,password);}return{filename:tail.filename,payload,encrypted:tail.flag===1,fallback:false};}const boundary=findRawImageBoundary(b);if(boundary===null)throw new Error('找不到有效的附加資料或支援的圖片結尾');if(boundary===b.length)throw new Error('圖片結尾後沒有附加資料');const payload=b.slice(boundary);return{filename:'extracted.'+guessExtension(payload),payload,encrypted:false,fallback:true};}
