import{asU8,bitsToBytes,concatBytes,readU32be,u32be,u8ToBits}from'./bits.js';import{decrypt,encrypt,encryptedSize}from'./crypto.js';
export const LSB_HEADER_BYTES=5;
export function imageCapacityBytes(w,h){if(!Number.isInteger(w)||!Number.isInteger(h)||w<0||h<0)throw new RangeError('Invalid image dimensions');return Math.floor(w*h*3/8);}
export function requiredTextBytes(text,encrypted=false){const n=new TextEncoder().encode(text).length;return 5+(encrypted?encryptedSize(n):n);}
export function buildTextPacket(flag,payload){const b=asU8(payload);if(flag!==0&&flag!==1)throw new RangeError('Flag must be 0 or 1');return concatBytes(new Uint8Array([flag]),u32be(b.length),b);}
export function embedBytes(imageData,packet){const d=asU8(imageData.data??imageData);if(d.length%4)throw new RangeError('RGBA data length must be a multiple of 4');const bits=u8ToBits(packet),cap=d.length/4*3;if(bits.length>cap)throw new Error('容量不足：需要 '+bits.length+' bits，但圖片只有 '+cap+' bits');const out=new Uint8ClampedArray(d);let n=0;for(let i=0;i<out.length&&n<bits.length;i++)if((i&3)!==3)out[i]=(out[i]&254)|bits[n++];return out;}
export function extractBytes(imageData,count){const d=asU8(imageData.data??imageData);if(!Number.isSafeInteger(count)||count<0)throw new RangeError('Invalid byte count');if(count*8>d.length/4*3)throw new Error('圖片容量不足，無法讀取宣告的資料長度');const bits=new Uint8Array(count*8);let n=0;for(let i=0;i<d.length&&n<bits.length;i++)if((i&3)!==3)bits[n++]=d[i]&1;return bitsToBytes(bits);}
export function inspectTextPacket(imageData){const h=extractBytes(imageData,5),flag=h[0],length=readU32be(h,1);if(flag!==0&&flag!==1)throw new Error('找不到有效的暗像文字資料');const cap=Math.floor(asU8(imageData.data??imageData).length/4*3/8);if(length>cap-5)throw new Error('隱藏資料長度無效或圖片已損毀');return{flag,length};}
export async function hideTextInImage(imageData,text,password=''){const plain=new TextEncoder().encode(text),payload=password?await encrypt(plain,password):plain;return embedBytes(imageData,buildTextPacket(password?1:0,payload));}
export async function extractTextFromImage(imageData,password=''){const{flag,length}=inspectTextPacket(imageData),packet=extractBytes(imageData,5+length);let payload=packet.slice(5);if(flag===1){if(!password)throw new Error('此內容已加密，請輸入密碼');payload=await decrypt(payload,password);}try{return{text:new TextDecoder('utf-8',{fatal:true}).decode(payload),encrypted:flag===1};}catch{throw new Error('隱藏文字不是有效的 UTF-8 資料');}}
