import{extractTextFromImage,hideTextInImage,imageCapacityBytes,requiredTextBytes}from'./lib/lsb.js';import{appendFileToImage,extractFileFromImage}from'./lib/fileAppend.js';
const $=s=>document.querySelector(s),status=(id,msg,ok=false)=>{const e=$(id);e.textContent=msg;e.className='status '+(ok?'success':'error');},bytes=f=>f.arrayBuffer().then(x=>new Uint8Array(x));
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');});
document.querySelectorAll('.eye').forEach(b=>b.onclick=()=>{const i=b.previousElementSibling;i.type=i.type==='password'?'text':'password';b.setAttribute('aria-label',i.type==='password'?'顯示密碼':'隱藏密碼');});
let imageInfo=null;async function loadPixels(file){const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0);bitmap.close();return{canvas,ctx,data:ctx.getImageData(0,0,canvas.width,canvas.height)};}
function updateCapacity(){const text=$('#ht-text').value,encrypted=!!$('#ht-pass').value,need=requiredTextBytes(text,encrypted),cap=imageInfo?imageCapacityBytes(imageInfo.canvas.width,imageInfo.canvas.height):0,over=need>cap;$('#capacity').textContent=imageInfo?'容量 '+cap.toLocaleString()+' bytes · 需要 '+need.toLocaleString()+' bytes':'請先選擇圖片';$('#capacity').classList.toggle('over',over);$('#ht-run').disabled=!imageInfo||!text||over;}
$('#ht-image').onchange=async e=>{try{imageInfo=await loadPixels(e.target.files[0]);updateCapacity();}catch{imageInfo=null;status('#ht-status','無法讀取圖片');}};$('#ht-text').oninput=updateCapacity;$('#ht-pass').oninput=updateCapacity;
$('#ht-run').onclick=async()=>{try{const out=await hideTextInImage(imageInfo.data,$('#ht-text').value,$('#ht-pass').value);imageInfo.data.data.set(out);imageInfo.ctx.putImageData(imageInfo.data,0,0);imageInfo.canvas.toBlob(blob=>download('#ht-download',blob,'暗像.png'),'image/png');status('#ht-status','沖印完成：輸出為無損 PNG。',true);}catch(e){status('#ht-status',e.message);}};
$('#rt-run').onclick=async()=>{try{const file=$('#rt-image').files[0];if(!file)throw new Error('請選擇圖片');const img=await loadPixels(file),result=await extractTextFromImage(img.data,$('#rt-pass').value);$('#rt-result').textContent=result.text;$('#rt-result').hidden=false;status('#rt-status',result.encrypted?'已成功解密並取出文字。':'已取出明文。',true);}catch(e){$('#rt-result').hidden=true;status('#rt-status',e.message);}};
function download(sel,blob,name){const a=$(sel);if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);a.dataset.url=URL.createObjectURL(blob);a.href=a.dataset.url;a.download=name;a.hidden=false;}
$('#hf-run').onclick=async()=>{try{const image=$('#hf-image').files[0],file=$('#hf-file').files[0];if(!image||!file)throw new Error('請同時選擇圖片與要藏入的檔案');const out=await appendFileToImage(await bytes(image),await bytes(file),file.name,$('#hf-pass').value);download('#hf-download',new Blob([out],{type:image.type}),image.name);status('#hf-status','封存完成；原始圖片位元組未重新編碼。',true);}catch(e){status('#hf-status',e.message);}};
$('#rf-run').onclick=async()=>{try{const image=$('#rf-image').files[0];if(!image)throw new Error('請選擇圖片');const r=await extractFileFromImage(await bytes(image),$('#rf-pass').value);download('#rf-download',new Blob([r.payload]),r.filename);status('#rf-status',r.fallback?'已用圖片邊界 fallback 取出原始附加資料。':'已讀取 STEGOFL1 封包。',true);}catch(e){status('#rf-status',e.message);}};
